In [3]:

import numpy as np
import cv2 as cv
img =cv.imread("D:\IMG processing lab\MicrosoftTeams-image (2).png",0)
sobely = cv.Sobel(img,-1,0,1,ksize=3)
cv.imwrite('D:\IMG processing lab\MicrosoftTeams-image (2).png',sobely)
print(sobely)
print(sobely.shape)
c=0
ar=[]
ar2=[]
list=[]
for row in range(0,sobely.shape[0]):
    for column in range(0,sobely.shape[1]):
        if sobely[row][column]==255:
            c=c+1
            ar.append(row)
            if ar2.count(row) < 1:
                ar2.append(row)
for i in ar2:
    c=ar.count(i)
    print(str(i)+" no.of times "+str(c))
    list.append(c)
m=max(list)
print("Largest value is :-",max(list))

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
(208, 511)
73 no.of times 458
117 no.of times 141
162 no.of times 249
Largest value is :- 458
