In [1]:
import cv2

ModuleNotFoundError: No module named 'cv2'

In [2]:
pip install cv2


Note: you may need to restart the kernel to use updated packages.


ERROR: Could not find a version that satisfies the requirement cv2
ERROR: No matching distribution found for cv2


In [1]:
pip install cv2 module

Note: you may need to restart the kernel to use updated packages.


ERROR: Could not find a version that satisfies the requirement cv2
ERROR: No matching distribution found for cv2


In [2]:
pip install opencv-python

In [3]:
import cv2


In [1]:
import cv2
img=cv2.imread("D:/IMG processing lab/ford-mustang-the-crew-2-4k.jpg")
print(img)
print(type(img))
cv2.imshow('Orignal Image',img)
ab=img
cv2.imwrite("D:/IMG processing lab/otp1.jpg",ab)
cv2.imread("D:/IMG processing lab/otp1.jpg")
print(ab)
cv2.imshow('Lab img',ab)
cv2.waitKey(0)


[[[58 53 52]
  [59 54 53]
  [58 54 53]
  ...
  [53 55 55]
  [55 57 57]
  [55 60 59]]

 [[57 52 51]
  [59 54 53]
  [59 55 54]
  ...
  [54 56 56]
  [56 58 58]
  [55 60 59]]

 [[56 51 50]
  [58 53 52]
  [59 55 54]
  ...
  [55 57 57]
  [54 59 58]
  [55 60 59]]

 ...

 [[28 28 28]
  [28 28 28]
  [29 29 29]
  ...
  [29 29 29]
  [29 29 29]
  [29 29 29]]

 [[28 28 28]
  [29 29 29]
  [28 28 28]
  ...
  [29 29 29]
  [29 29 29]
  [29 29 29]]

 [[28 28 28]
  [29 29 29]
  [28 28 28]
  ...
  [29 29 29]
  [29 29 29]
  [29 29 29]]]
<class 'numpy.ndarray'>
[[[58 53 52]
  [59 54 53]
  [58 54 53]
  ...
  [53 55 55]
  [55 57 57]
  [55 60 59]]

 [[57 52 51]
  [59 54 53]
  [59 55 54]
  ...
  [54 56 56]
  [56 58 58]
  [55 60 59]]

 [[56 51 50]
  [58 53 52]
  [59 55 54]
  ...
  [55 57 57]
  [54 59 58]
  [55 60 59]]

 ...

 [[28 28 28]
  [28 28 28]
  [29 29 29]
  ...
  [29 29 29]
  [29 29 29]
  [29 29 29]]

 [[28 28 28]
  [29 29 29]
  [28 28 28]
  ...
  [29 29 29]
  [29 29 29]
  [29 29 29]]

 [[28 28 28]
  [29

-1

In [2]:
import cv2
img=cv2.imread("D:/IMG processing lab/ford-mustang-the-crew-2-4k.jpg")
print(img)
print(type(img))
cv2.imshow('Orignal Image',img)
cv2.waitKey(0)



[[[58 53 52]
  [59 54 53]
  [58 54 53]
  ...
  [53 55 55]
  [55 57 57]
  [55 60 59]]

 [[57 52 51]
  [59 54 53]
  [59 55 54]
  ...
  [54 56 56]
  [56 58 58]
  [55 60 59]]

 [[56 51 50]
  [58 53 52]
  [59 55 54]
  ...
  [55 57 57]
  [54 59 58]
  [55 60 59]]

 ...

 [[28 28 28]
  [28 28 28]
  [29 29 29]
  ...
  [29 29 29]
  [29 29 29]
  [29 29 29]]

 [[28 28 28]
  [29 29 29]
  [28 28 28]
  ...
  [29 29 29]
  [29 29 29]
  [29 29 29]]

 [[28 28 28]
  [29 29 29]
  [28 28 28]
  ...
  [29 29 29]
  [29 29 29]
  [29 29 29]]]
<class 'numpy.ndarray'>


-1

In [3]:
import cv2
img=cv2.imread("D:/IMG processing lab/ford-mustang-the-crew-2-4k.jpg",0)
print(img)
print(type(img))
cv2.imshow('Grayscale Image',img)
x=img
cv2.imwrite("D:/IMG processing lab/grayimg.jpg",x)
cv2.waitKey(0)

[[53 54 54 ... 55 57 59]
 [52 54 55 ... 56 58 59]
 [51 53 55 ... 57 58 59]
 ...
 [28 28 29 ... 29 29 29]
 [28 29 28 ... 29 29 29]
 [28 29 28 ... 29 29 29]]
<class 'numpy.ndarray'>


-1

In [5]:
import cv2
img=cv2.imread("D:/IMG processing lab/grayimg.jpg",-1)
cv2.imshow("Original img:-",img)
print(img)
print(type(img))
cv2.imshow('Transparency image',img)
cv2.waitKey(0)

[[53 54 54 ... 55 57 59]
 [52 53 55 ... 56 58 59]
 [51 53 55 ... 57 58 59]
 ...
 [29 29 29 ... 29 29 29]
 [28 28 28 ... 29 29 29]
 [29 29 29 ... 29 29 29]]
<class 'numpy.ndarray'>


-1

In [8]:
import cv2
img=cv2.imread("D:/IMG processing lab/ford-mustang-the-crew-2-4k.jpg")
rs=cv2.resize(img,(320,320))
cv2.imwrite("D:/IMG processing lab/resizeimg.jpg",rs)


True

In [6]:
import cv2
img=cv2.imread("D:/IMG processing lab/ford-mustang-the-crew-2-4k.jpg",1)
cv2.imshow("color image",img)
print(img)
print(type(img))
cv2.waitKey(0)

[[[58 53 52]
  [59 54 53]
  [58 54 53]
  ...
  [53 55 55]
  [55 57 57]
  [55 60 59]]

 [[57 52 51]
  [59 54 53]
  [59 55 54]
  ...
  [54 56 56]
  [56 58 58]
  [55 60 59]]

 [[56 51 50]
  [58 53 52]
  [59 55 54]
  ...
  [55 57 57]
  [54 59 58]
  [55 60 59]]

 ...

 [[28 28 28]
  [28 28 28]
  [29 29 29]
  ...
  [29 29 29]
  [29 29 29]
  [29 29 29]]

 [[28 28 28]
  [29 29 29]
  [28 28 28]
  ...
  [29 29 29]
  [29 29 29]
  [29 29 29]]

 [[28 28 28]
  [29 29 29]
  [28 28 28]
  ...
  [29 29 29]
  [29 29 29]
  [29 29 29]]]
<class 'numpy.ndarray'>


-1

In [10]:
import cv2
import numpy as np
  
# Read First Image
img1 = cv2.imread('D:/IMG processing lab/resizeimg.jpg')
  
# Read Second Image
img2 = cv2.imread('D:/IMG processing lab/resizeimg.jpg')
  
Hori = np.concatenate((img1, img2), axis=1)
  
cv2.imshow('HORIZONTAL', Hori)
  
cv2.waitKey(0)
cv2.destroyAllWindows()

In [19]:
import cv2
img=cv2.imread("D:/IMG processing lab/resizeimg.jpg")
x=img[100][168]
print(x)
# cv2.imshow('Color Image',img)
# cv2.imshow('image pixel',x)
cv2.waitKey(0)

[209 207 199]


-1

In [1]:
import cv2
img=cv2.imread("D:/IMG processing lab/resizeimg.jpg",0)
print(img[100][50])
# cv2.imshow('Grayscale Image',img)
cv2.waitKey(0)


232


-1

In [23]:
import cv2
img=cv2.imread("D:/IMG processing lab/resizeimg.jpg",-1)
print(img[100][50])
# cv2.imshow('Transparent Image',img)
cv2.waitKey(0)

[238 238 221]


-1

In [21]:
import cv2
import numpy as np
img=cv2.imread("D:/IMG processing lab/resizeimg.jpg")
px=img[100,100]
print(px)
blue=img[100,100,0]
print("Blue:-",blue)
green=img[100,100,1]
print("Green:-",green)
red=img[100,100,2]
print("Red:-",red)


[206 200 195]
Blue:- 206
Green:- 200
Red:- 195


In [22]:
import cv2 
img=cv2.imread("D:/IMG processing lab/resizeimg.jpg")
h, w, c = img.shape
print("height :- " ,h)
print("width :- " ,w)
print("channels :- " ,c)
for i in range(h) :
    print(img[i,0])

height :-  320
width :-  320
channels :-  3
[58 52 53]
[57 51 52]
[57 52 51]
[57 52 51]
[58 53 52]
[59 54 53]
[59 54 53]
[59 54 53]
[60 55 54]
[60 55 54]
[60 55 54]
[60 55 54]
[60 55 54]
[61 56 55]
[61 56 55]
[61 56 55]
[62 55 52]
[63 56 53]
[63 56 53]
[64 57 54]
[65 58 55]
[66 59 56]
[67 60 57]
[68 61 58]
[67 60 57]
[68 61 58]
[68 61 58]
[68 61 58]
[72 63 60]
[72 63 60]
[72 63 60]
[72 63 60]
[72 63 59]
[72 63 59]
[71 62 58]
[71 62 58]
[72 63 59]
[73 64 60]
[74 65 61]
[75 66 62]
[78 67 63]
[79 68 64]
[79 68 64]
[80 69 65]
[81 70 66]
[81 70 66]
[81 70 66]
[82 71 67]
[83 71 67]
[84 72 68]
[84 72 68]
[85 73 69]
[88 76 70]
[91 79 73]
[93 81 75]
[95 83 77]
[95 83 77]
[97 85 79]
[100  87  79]
[100  87  79]
[101  88  80]
[102  89  81]
[103  90  82]
[104  91  83]
[103  89  83]
[102  88  82]
[101  87  81]
[102  88  82]
[103  89  83]
[106  92  86]
[109  95  89]
[111  97  91]
[112  98  92]
[114 100  94]
[115 101  95]
[115 101  95]
[118 104  98]
[119 105  99]
[120 106 100]
[121 107 101]
[123 107 1

In [23]:
for i in range(w) :
    print(img[0,i])


[58 52 53]
[60 54 55]
[62 57 56]
[62 57 56]
[59 54 53]
[56 51 50]
[57 52 51]
[60 55 54]
[63 58 55]
[63 58 55]
[61 57 56]
[58 54 53]
[55 51 50]
[53 49 48]
[54 50 49]
[55 51 50]
[56 51 53]
[53 50 52]
[60 56 62]
[66 65 74]
[85 84 94]
[ 92  93 107]
[ 88  88 104]
[ 96  98 116]
[ 98 100 118]
[101 104 119]
[ 91  91 107]
[79 79 91]
[75 74 84]
[74 72 78]
[79 72 79]
[80 75 77]
[74 69 70]
[68 64 63]
[65 60 59]
[66 61 60]
[73 65 65]
[78 70 70]
[84 72 72]
[86 74 74]
[88 76 74]
[87 75 73]
[88 76 74]
[88 76 74]
[88 76 74]
[88 76 74]
[86 77 74]
[87 78 75]
[90 79 75]
[92 81 77]
[94 82 76]
[99 87 81]
[119 105  99]
[144 130 124]
[158 144 138]
[160 146 140]
[163 147 140]
[164 148 141]
[165 149 143]
[166 150 144]
[167 151 145]
[168 152 146]
[170 154 148]
[172 156 150]
[170 156 150]
[170 156 150]
[170 156 150]
[172 158 152]
[173 159 153]
[174 160 154]
[174 160 154]
[174 160 154]
[174 160 154]
[175 161 155]
[175 161 155]
[176 162 156]
[177 163 157]
[177 163 157]
[178 163 160]
[179 164 161]
[181 164 161]
[183